#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Command line for a C++ automatic builder
"""
__author__ = 'Mauro Bruni'

from core import build

def main(*argv):
    if len(argv) >= 2:
        try:
            build(argv[1])
        except IOError, e:
            print e
    else:
        print 'usage: {0} file.cpp'.format(*argv)

if __name__ == '__main__':
    from sys import argv
    main(*argv)
